ui:
  cors:
    allowed-origins: http://ui:3000, http://api:8081

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/bank?useSSL=false
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/kursovoiRealm
          jwk-set-uri: http://keycloak:8080/auth/realms/kursovoiRealm/protocol/openid-connect/certs
